### ISSUE TITLE
Reference back to parent causes infinite recursion

### ISSUE THREAD

**Issue by Graham42** [arey/hibernate-hydrate#10]
Version: hibernate4-hydrate 2.1

If an Entity has a child, and that child has a reference back to the parent, `LazyLoadingUtil.deepHydrate` will cause infinite recursion.

**Comment by arey** [comment]
ManyToOne bidirectionnel mapping was already tested in TestLazyLoadingUtil (see Customer entity).
So I've added a test with OneToOne bidirectionnel relationship (mappyBy) but I cannot reproduce this issue. See TestIssue10.

Could you please give me a mapping sample will cause the infinite recursion?

**Comment by Graham42** [comment]
Sorry I found it was actually a problem with my code, closing this as invalid.
