### ISSUE TITLE
Debug spam

### ISSUE THREAD

**Issue by Graham42** [arey/hibernate-hydrate#11]
Version: hibernate4-hydrate 2.1

When I add this dependency to my project, all database queries are being logged as debug.

```
...
17:27:37.119 [main] DEBUG org.hibernate.SQL - select //... some query
17:27:37.120 [main] DEBUG o.h.l.p.e.p.i.ResultSetProcessorImpl - Preparing collection intializer : //... details
17:27:37.120 [main] DEBUG o.h.l.p.e.p.i.ResultSetProcessorImpl - Starting ResultSet row #0
17:27:37.120 [main] DEBUG o.h.l.p.e.p.i.CollectionReferenceInitializerImpl - Found row of collection: //... details
17:27:37.120 [main] DEBUG o.h.l.p.e.p.i.ResultSetProcessorImpl - Starting ResultSet row #1
...
...
```

**Comment by arey** [comment]
I suppose those debug logs are generated by the logback-classic.jar your project depends by maven transitivity. I've changed its maven scope to test.

**Comment by arey** [comment]
@Graham42 by waiting the next release, you could exclude the ch.qos.logback:logback-classic artefact.
