### ISSUE TITLE
Re-enable test if HHH-15713 has been fixed

### ISSUE THREAD

**Issue by markusheiden** [arey/hibernate-hydrate#34]
Due to the Hibernate 6 bug HHH-15713 the test `TestIssue3#listWithEmbeddableClass()` fails and thus has been disabled.

Re-enable the test as soon as HHH-15713 has been fixed in Hibernate 6.

**Comment by arey** [comment]
Should be fix in Hibernate ORM [6.1.6](https://hibernate.atlassian.net/issues/?jql=project%20%3D%20%22HHH%22%20AND%20fixVersion%20%3D%20%226.1.6%22)

**Comment by arey** [comment]
Fix by PR https://github.com/arey/hibernate-hydrate/pull/35

**Comment by arey** [comment]
Don't seems to work: https://github.com/arey/hibernate-hydrate/actions/runs/3664545005/jobs/6195027481
```
Error:  com.javaetmoi.core.persistence.hibernate.TestIssue3.listWithEmbeddableClass  Time elapsed: 0.037 s  <<< ERROR!
org.hibernate.sql.ast.tree.from.UnknownTableReferenceException: Unable to determine TableReference (`SubPlan`) for `com.javaetmoi.core.persistence.hibernate.listWithEmbeddable.Plan.transfers.events`
```

**Comment by markusheiden** [comment]
Strange. Locally it works for me.

**Comment by markusheiden** [comment]
I missed the hibernate-6.0 profile.

https://github.com/arey/hibernate-hydrate/pull/37

Anyway, I didn't manage to successfully use a prior Hibernate version for the "last" build.

**Comment by arey** [comment]
Thank you Markus. The CI build is fixed :-)
